### ISSUE TITLE
Alternative to aliases

### ISSUE THREAD

**Issue by aravindet** [usegraffy/graffy#10]
@baopham @email2vimalraj 

The consumer APIs (which change to read, write and watch) could gain a path argument to avoid having to implement aliases.

By and large, Graffy encourages granular queries; if a component has the sort of data need that requires aliases, it might be better served by just making two queries.

However using dynamic keys in queries comes with a bit of boilerplate that could be eliminated.

## Problem

```js
const postId = get_post_id_somewhere();
result = await gs.read({ posts: { [postId]: { ... } });
const what_i_really_want = result.posts[postId];
```

It feels even worse when using filter parameters:

```js
const filter = encodeKey({ tags: ['tech', 'javascript'] }); // This is some opaque string.
result = await gs.read({ filteredPostsByTime: { [filter]: [ { first: 10 }, {...} ] });
const what_i_really_want = result.posts[filter];
```

I have to store the encoded filter into a variable even though it has no meaning or use outside that query.

## Solution

I feel that a better API might be:

```js
const postId = get_post_id_somewhere();
const just_the_post = gs.read( ['posts', postId], { ... });
```

or with the filter:

```js
const filteredPosts = gs.read([ 'filteredPostsByTime', encodeKey(...) ], [ { first: 10 }, { ... } ]);
```

What say?

In read/write/watch, we would wrap the query in the path before passing to .call(), and unwrap the results before returning.

**Comment by email2vimalraj** [comment]
Hope this is been taken care through the PR: https://github.com/usegraffy/graffy/pull/13

**Comment by aravindet** [comment]
Yes! I have added the path parameter, so it should not be necessary anymore.
