### ISSUE TITLE
Typescript checking, emitting definitions

### ISSUE THREAD

**Issue by aravindet** [usegraffy/graffy#22]
Primary goal: Add typings to the published NPM modules.
Secondary goal: Get type checks into the development workflow for Graffy itself.

The preferred approach is to use JSDoc-style function annotations (that TypeScript supports) rather than converting to Typescript syntax.

**Comment by Ashniu123** [comment]
Can we use a `types` folder which has it all written in? Many popular repos use this method to get the benefits of typescript without rewriting code in it.
